[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14

build_flags =
    -DWIFI_SSID=\"TU_RED\"
    -DWIFI_PASS=\"TU_CLAVE\"
    -DMQTT_HOST=\"server-local.tail9af6ac.ts.net\"
    -DMQTT_PORT=1883
    -DMQTT_USER=\"device\"
    -DMQTT_PASS=\"esp32\"
    -DDEVICE_ID=\"esp32-pio-01\"

[env:esp32dev_ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = 192.168.1.100

[env:esp8266]
platform = espressif8266
board = esp12e
framework = arduino

monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0
    adafruit/DHT sensor library@^1.4.6

build_flags =
    -DWIFI_SSID=\"TU_RED\"
    -DWIFI_PASS=\"TU_CLAVE\"
